name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'client/**'

jobs:
  run-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: client
        run: yarn

      - name: Build client
        working-directory: client
        run: yarn build
