name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'client/**'

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: client
        run: yarn

      - name: Test client
        working-directory: client
        run: yarn test
